### ISSUE TITLE
How to tag custom data

### ISSUE THREAD

**Issue by DavidSagan** [campa-consortium/pals#47]
The issue is how to tag custom data that a program might want to store in the lattice file. Requiring that custom data names be declared enables checking for spelling errors which is very useful. One possibility to require, for example, all custom data names to end with the letter "C". If the custom data is expressed as a tree only the root name needs to be so marked. For example:
```yaml
This_CustomC:
  component1: ...
  component2: ...
```

Another possibility is for custom names to be explicitly declared like:
```yaml
CustomNames:
  this_custom_name
  that_custom_name
  ...
```
One option is that these possibilities can be combined. 
Anyone have any thoughts?

**Comment by ax3l** [comment]
Great idea.

Natural from naming in other standards, e.g., XML schemas and JSON schemas, it to use a _prefix_ to tag custom properties.

Example:
```
MyQuad:
  type "quadrupole"
  ds: 1.2
  k: -1.0
  custom_pv_variable: 42
  custom_warpx_slice: 12
```

**Comment by DavidSagan** [comment]
Or use `custom` as a prefix for custom information like:
```
Quadrupole:
  name: myquad
  length: 1.2
  MagneticMultipoleP:
    kn1: -1.0
  custom_impactx:
      nslice: 12
      space_charge: 2D
```
Here `custom_impactx` is treated as containing custom data.
